config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  get 'admin' => 'admin#index'

  resources :organizations
    resources :exhibits do
      resources :posts, shallow: true

      member do
        put :regenerate_slug
      end
    end

  resources :users do
    member do
      put :make_admin
    end
  end

  resources :images

end

app/models/exhibit.rb
class Exhibit < ActiveRecord::Base
	has_many :posts
	belongs_to :user
	belongs_to :organization

	has_attached_file :image, :styles => { :medium => "800x800>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	extend FriendlyId
		friendly_id :name, use: :slugged

end

app/controllers/exhibits_controller.rb
class ExhibitsController < ApplicationController
  before_action :set_exhibit, only: [:show, :edit, :update, :destroy]

  layout 'admin'

  # GET /exhibits
  # GET /exhibits.json
  def index
    @exhibits = Exhibit.all
  end

  # GET /exhibits/1
  # GET /exhibits/1.json
  def show

    @exhibit = Exhibit.friendly.find(params[:id])
    @exposts = @exhibit.posts.where(published: "true")
    @organization = Organization.find(@exhibit.organization_id)  
    render :layout => 'application' 

  end

  # GET /exhibits/new
  def new
    @exhibit = Exhibit.new
  end

  # GET /exhibits/1/edit
  def edit
  end

  # POST /exhibits
  # POST /exhibits.json
  def create
    @exhibit = Exhibit.new(exhibit_params)
    @exhibit.user_id = current_user.id

    respond_to do |format|
      if @exhibit.save
        format.html { redirect_to @exhibit, notice: 'Exhibit was successfully created.' }
        format.json { render :show, status: :created, location: @exhibit }
      else
        format.html { render :new }
        format.json { render json: @exhibit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exhibits/1
  # PATCH/PUT /exhibits/1.json
  def update
    respond_to do |format|
      if @exhibit.update(exhibit_params)
        format.html { redirect_to @exhibit, notice: 'Exhibit was successfully updated.' }
        format.json { render :show, status: :ok, location: @exhibit }
      else
        format.html { render :edit }
        format.json { render json: @exhibit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exhibits/1
  # DELETE /exhibits/1.json
  def destroy
    @exhibit.destroy
    respond_to do |format|
      format.html { redirect_to exhibits_url, notice: 'Exhibit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def regenerate_slug

    @exhibittoregen = Exhibit.find(params[:id])
    @exhibittoregen.slug = nil
    @exhibittoregen.save!

    redirect_to edit_exhibit_path(@exhibittoregen)

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exhibit
      @exhibit = Exhibit.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exhibit_params
      params.require(:exhibit).permit(:name, :description, :image, :organization_id, :user_id, :slug)
    end
end

app/helpers/exhibits_helper.rb
module ExhibitsHelper
end

app/views/exhibits/_exhibitlist.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Organization</th>
      <th>Description</th>
      <th>URL Slug</th>
      <th>Exhibit Logo</th>
      <th>Exhibit Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @exhibits.each do |exhibit| %>
      <tr>
        <td><%= link_to exhibit.name, exhibit_posts_path(exhibit) %></td>
        <td><%= exhibit.organization.name %></td>
        <td><%= truncate(exhibit.description, length: 50) %></td>
        <td><code><%= exhibit.slug %></code></td>
        <td><%= image_tag exhibit.image.url(:thumb) %></td>

        <td>
          <div class="btn-group trailer" role="group" aria-label="...">
            <%= link_to exhibit.name + ' Admin', exhibit_posts_path(exhibit), :type => "button", :class => "btn btn-default" %> 
            <%= link_to exhibit.name + ' Public Site', exhibit_path(exhibit), :type => "button", :class => "btn btn-default" %>
            <%= link_to 'Edit', edit_exhibit_path(exhibit), :type => "button", :class => "btn btn-warning" %>
            <%= link_to 'Delete', exhibit, :type => "button", :class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/exhibits/_form.html.erb
<%= simple_form_for @exhibit do |f| %>
  <% if @exhibit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exhibit.errors.count, "error") %> prohibited this exhibit from being saved:</h2>

      <ul>
      <% @exhibit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :name, label: 'Name:', error: 'Whoops! We need a name here :)', wrapper_html: { class: 'form-group' }, input_html: { class: 'form-control' } %>
   <label>URL Slug</label>
  <code><%= @exhibit.slug %></code>
  <%= link_to 'Regenerate Slug', regenerate_slug_exhibit_path(@exhibit.id), :method => :put, :type => "button", :class => "btn btn-default", data: { confirm: 'Woah there! This will change any links currently set to /' + @exhibit.slug + ' to a slug based on the latest name: ' + @exhibit.name } %>

  <%= f.input :description, label: 'Description:', error: 'Whoops! We need a description here :)', wrapper_html: { class: 'form-group' }, input_html: { class: 'form-control', rows: 10, cols: 10 } %>
  <div class="alert alert-info" role="alert">
    <p>This description field uses Markdown syntax <%= link_to 'read the reference', 'http://daringfireball.net/projects/markdown/syntax' %> to use in the description field above.</p>
  </div>
  <%= f.association :organization, wrapper_html: { class: 'form-group' }, input_html: { class: 'form-control' } %>

  <p class="help-block">If the organization you're looking for is not availbale, please create one before creating or updating your Exhibit | <%= link_to 'Create Organization',new_organization_path, :class => "btn btn-default"  %></p> 

  <label for="exampleInputFile">Exhibit Header Image Upload:</label>
  <%= f.file_field :image, inline_label: 'Logo Image:', error: 'Whoops! We need an image here :)', :class => "trailer" %>
 
  <%= f.button :submit, :class => "btn-success" %>

<% end %>

app/views/exhibits/edit.html.erb
<div class="col-md-12">
	<div class="btn-group" role="group" aria-label="...">
	 	 <%= link_to '< To Admin Home', admin_path, :type => "button", :class => "btn btn-default"  %>
		<%= link_to @exhibit.name + ' Exhibit Posts', exhibit_posts_path(@exhibit), :type => "button", :class => "btn btn-default" %> 
		<%= link_to 'Destroy Exhibit', @post, :type => "button", :class => "btn btn-danger", method: :delete, data: { confirm: 'Are really really sure?' } %>
	</div>


<h1>Editing Exhibit </h1>

<%= render 'form' %>

</div>

app/views/exhibits/index.html.erb
<div class="col-md-12">
<p id="notice"><%= notice %></p>


<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Exhibits</h3>
  </div>
  <div class="panel-body">
  <%= link_to 'New Exhibit', new_exhibit_path, :class => "btn btn-success right" %>
    <%= render 'exhibitlist' %>
  </div>
</div>




</div>

app/views/exhibits/new.html.erb
<%= link_to 'Back to Admin', admin_path %>

<h1>New Exhibit</h1>

<%= render 'form' %>

app/views/exhibits/show.html.erb
<% if current_user.try(:admin?) %>
	<div class="col-md-12">
		<div class="alert alert-info admin" role="alert"><strong>Admin Actions:</strong> These functions are only available to site admins.  

			<div class="btn-group" role="group" aria-label="...">

				<%= link_to @exhibit.name + ' Exhibit Admin', exhibit_posts_path(@exhibit), :type => "button", :class => "btn btn-default"  %>
				<%= link_to 'Edit Exhibit', edit_exhibit_path(@exhibit), :type => "button", :class => "btn btn-warning" %> 
			</div>

			<p id="notice"><%= notice %></p>

		</div>
	</div>

<% else %>
<% end %>


<div class="col-md-12">

	<div class="nav-links">
		<%= link_to 'Pin it', "http://pinterest.com/pin/create/button/?url=" + request.original_url + "&amp;description=Check+out+the+hear+me+exhibit..." %> 
		<%= link_to 'Tweet it', "http://twitter.com/share?url=" + request.original_url + "&amp;text=Check+out+Hear+Me:+Your+story+through+tattoos...&amp;hashtags=#hearme" %> 
		<%= link_to 'Share on FB', "http://www.facebook.com/share.php?u=" + request.original_url %>
	</div>

	<div class="center homelogo">
		<%= link_to (image_tag @exhibit.image.url(:medium)), exhibit_path(@exhibit) %>
	</div>

</div>

<div class="col-md-12">

	<h2><%= @exhibit.name %></h2>

</div>

<div class="col-md-12">
	<div class="tilegrid">
		<% @exposts.each do |post| %>
			<div class="tile">
				<h3 ><%= link_to post.title, post_path(post), :class => "truncate" %></h3>
				<% post.images.limit(1).each do |image| %>
				<%= link_to (image_tag image.photo.url(:small), :class => "clear"), post_path(post) %>
				<% end %>
			</div>
		<% end %>
	</div>
</div>	

<div class="col-md-12">
	<div class="clear header">
		<h3>About Us</h3>
		<div class="small-header tailer">
			<%= image_tag @organization.image.url(:thumb), :class => "left margin-r"  %>
			<h2 class="margin-clear"><%= @organization.name %></h2>
			<p><%= @organization.description %></p>
		</div>
	</div>
</div>