config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  get 'admin' => 'admin#index'

  resources :organizations
    resources :exhibits do
      resources :posts, shallow: true

      member do
        put :regenerate_slug
      end
    end

  resources :users do
    member do
      put :make_admin
    end
  end

  resources :images

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :exhibit
	belongs_to :user
	validates_presence_of :user, :exhibit
	has_many :images, :dependent => :destroy

	accepts_nested_attributes_for :images

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]


  # GET /posts
  # GET /posts.json
  def index

    @posts = Post.where("exhibit_id = ?", Exhibit.friendly.find(params[:exhibit_id])).order(updated_at: :desc)
    @exhibit = Exhibit.friendly.find(params[:exhibit_id])

    render :layout => 'admin' 
  end

  # GET /posts/1
  # GET /posts/1.json
  def show

     @post = Post.find(params[:id])
     post = Post.find(params[:id])
     @exhibit = Exhibit.friendly.find(Post.find(post.id).exhibit_id)
    @organization = Organization.find(@exhibit.organization_id)
    @postimages = Image.where(post_id: (params[:id]))
  end

  # GET /posts/new
  def new
  
    @exhibit = Exhibit.friendly.find(params[:exhibit_id])
    @post = Post.new
    @path = ([@exhibit, @post])
    3.times {@post.images.build}
  
      render :layout => 'admin' 

    # 3.times { @post.images.build } # ... and this
  end

  # GET /posts/1/edit
  def edit
    @exhibit = Post.find(params[:id]).exhibit_id
    @post = Post.find(params[:id])
    @path = (@post)
    1.times {@post.images.build}

    render :layout => 'admin' 
    # 3.times { @post.images.build } # ... and this

  end

  # POST /posts
  # POST /posts.json
  def create
    @exhibit = Exhibit.friendly.find(params[:exhibit_id])
    @post = @exhibit.posts.new(post_params)
    @post.user_id = current_user.id


    respond_to do |format|
      if @post.save

      # if params[:photos]
      #   #===== The magic is here ;)
      #   params[:photos].each { |photo|
      #     @post.images.create(image: photo)
      #   }
      # end

        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update

    @exhibit = Post.find(params[:id]).exhibit_id
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update(post_params)

      #   if params[:photos]
      #   #===== The magic is here ;)
      #   params[:photos].each { |photo|
      #     @post.images.create(image: photo)
      #   }
      # end


        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @exhibit = Post.find(params[:id]).exhibit_id
    @post.destroy
    respond_to do |format|
      format.html { redirect_to exhibit_posts_path(@exhibit), notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :exhibit_id, :post_id, :published, images_attributes: [:photo, :id])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for @path, :html => { :multipart => true } do |p| %>
  <div class="form-inputs">
  <%= p.input :title, label: "Title:", wrapper_html: { class: 'form-group' }, input_html: { class: 'form-control' }  %>
  <%= p.input :description, as: :text, label: "Desc:", wrapper_html: { class: 'form-group' }, input_html: { class: 'form-control', rows: 10, cols: 10 } %>
  <div class="alert alert-info" role="alert">
    <p>This description field uses Markdown syntax <%= link_to 'read the reference', 'http://daringfireball.net/projects/markdown/syntax' %> to use in the description field above.</p>
  </div>
     
   <h3>Post Images:</h3>

      <table class="table table-striped">
      <thead>
        <tr>
          <th>Image</th>
          <th>Upload</th>
          <th>Actions</th>
        </tr>
      </thead>

      <tbody>

      <%= p.simple_fields_for :images do |ph| %>
          <% if ph.object.new_record? %>
            <tr>
              <td>Add a new image</td>
              <td><%= ph.file_field :photo %></td>
              <td></td>
            </tr>
          
          <% else %>
            <tr>
              <td><%= image_tag ph.object.photo.url(:thumb) %></td>
              <td><%= ph.file_field :photo %></tb>
              <td><%= link_to 'Delete', ph.object, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        <% end %>

        </tbody>
        </table>
    <label>Published: <label>
    <%= p.input_field :published, as: :boolean, boolean_style: :inline, class: 'checkbox checkbox-toggle' %>

    </div>


    <div class="form-actions header">
    <%= p.button :submit, :class => "btn-success" %>
    </div>
    <div class="trailer"></div>
<% end %>

app/views/posts/edit.html.erb
<div class="col-md-12">

	<div class="btn-group trailer" role="group" aria-label="...">
		<%= link_to 'Visit Post', @post, :type => "button", :class => "btn btn-default" %> 
		<%= link_to 'Exhibit Posts', exhibit_posts_path(@exhibit), :type => "button", :class => "btn btn-default" %>
		<%= link_to 'Delete', @post, :type => "button", :class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
	</div>


	<h1>Editing Posts</h1>

	<%= render 'form' %>

</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-8">


<div class="btn-group trailer" role="group" aria-label="...">
  <%= link_to '< To Admin Home', admin_path, :type => "button", :class => "btn btn-default"  %>
  <%= link_to @exhibit.name + ' Public Site', exhibit_path(@exhibit), :type => "button", :class => "btn btn-default" %>
  <%= link_to 'Edit Exhibit', edit_exhibit_path(@exhibit.id), :type => "button", :class => "btn btn-warning" %>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= @exhibit.name %> Posts</h3>
  </div>
  <div class="panel-body">



  <%= link_to 'New Post', new_exhibit_post_path, :class => "btn btn-success right" %>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Published Status</th>
          <th>Last Updated</th>
          <th>Actions</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td><%= link_to post.title, post %></td>
            <td><%= truncate(post.description, length: 60) %></td>
            <td>
              <%= simple_form_for post, :remote => true do |p| %>
                  <%= p.input_field :published, as: :boolean, boolean_style: :inline, class: 'checkbox checkbox-toggle auto-change' %>
                  <%= p.button :submit, style: "display:none;" %>
              
              <% end %>
            </td>
             <td><%= time_ago_in_words(post.updated_at) + ' ago' %></td>
            <td><%= link_to 'Edit', edit_post_path(post) %></td>
            <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>


  </div>
</div>


</div>

app/views/posts/new.html.erb
<%= link_to 'Back', exhibit_posts_path %>

<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<% if current_user.try(:admin?) %>
	<div class="col-md-12">
		<div class="alert alert-info admin" role="alert"><strong>Admin Actions:</strong> These functions are only available to site admins.  

			<div class="btn-group" role="group" aria-label="...">

				<%= link_to @exhibit.name + ' Exhibit', exhibit_path(@exhibit), :type => "button", :class => "btn btn-default"  %>
				<%= link_to @exhibit.name + ' Exhibit Admin', exhibit_posts_path(@exhibit), :type => "button", :class => "btn btn-default"  %>
				<%= link_to 'Edit Post', edit_post_path(@post), :type => "button", :class => "btn btn-warning" %> 
				<%= link_to 'Destroy Post', @post, :type => "button", :class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
			</div>

			<p id="notice"><%= notice %></p>

		</div>
	</div>

<% else %>
<% end %>



<div class="col-md-12">


	<div class="nav-links">
		<%= link_to 'Pin it', "http://pinterest.com/pin/create/button/?url=" + request.original_url + "&amp;description=Check+out+the+hear+me+exhibit..." %> 

		<%= link_to 'Tweet it', "http://twitter.com/share?url=" + request.original_url + "&amp;text=Check+out+Hear+Me:+Your+story+through+tattoos...&amp;hashtags=#hearme" %> 
		<%= link_to 'Share on FB', "http://www.facebook.com/share.php?u=" + request.original_url %>
	</div>

	<div class="center homelogo">
			<%= link_to (image_tag @exhibit.image.url(:medium)), exhibit_path(@exhibit) %>
	</div>

</div>

<div class="col-md-12">
	<h1><%= @post.title %></h1>
</div>


<div class="col-md-8">

	<ul class="bxslider">
		<% @postimages.each do |image| %>
			<li><%= image_tag image.photo.url(:medium) %></li>
		<% end %>
	</ul>

		<div id="bx-pager">
		<% @postimages.each_with_index do |image, index| %>
	 		<a data-slide-index="<%= index %>" href=""><%= image_tag image.photo.url(:thumb) %></a>
	 	<% end %>
	</div>

</div>
<div class="col-md-4">
<p><%= markdown(@post.description) %></p>	
</div>

<div class="col-md-12">

	<div class="clear header">
		<h3>About Us</h3>
		<div class="small-header tailer">
			<%= image_tag @organization.image.url(:thumb), :class => "left margin-r"  %>
			<h2 class="margin-clear"><%= @organization.name %></h2>
			<%= @organization.description %>
		</div>
	</div>
</div>