config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  get 'admin' => 'admin#index'

  resources :organizations
    resources :exhibits do
      resources :posts, shallow: true

      member do
        put :regenerate_slug
      end
    end

  resources :users do
    member do
      put :make_admin
    end
  end

  resources :images

end

app/models/organization.rb
class Organization < ActiveRecord::Base
	has_many :exhibits
	belongs_to :user

	has_attached_file :image, :styles => { :medium => "800x800>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  	  accepts_nested_attributes_for :exhibits

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
        render :layout => 'admin' 
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
        render :layout => 'admin' 
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
        render :layout => 'admin' 
  end

  # GET /organizations/1/edit
  def edit
        render :layout => 'admin' 
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)
    @organization.user_id = current_user.id

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name, :description, :image, :user_id)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= simple_form_for(@organization) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

	<%= f.input :name, label: 'Name:', error: 'Whoops! We need a name here :)', wrapper_html: { class: 'form-group' }, input_html: { class: 'form-control' }  %>
	<%= f.input :description, label: 'Description:', error: 'Whoops! We need a description here :)', wrapper_html: { class: 'form-group' }, input_html: { class: 'form-control' }  %>
	 <label for="exampleInputFile">Organization Logo Upload:</label>
	<%= f.file_field :image, label: 'Image:', error: 'Whoops! We need an image here :)', :class => "trailer" %>

  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn-success" %>
  </div>
<% end %>

app/views/organizations/_organizationlist.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Logo Image</th>
      <th>Org Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.name %></td>
        <td><%= truncate(organization.description, length: 50) %></td>
        <td> <%= image_tag organization.image.url(:thumb) %></td>

        <td>
          <div class="btn-group trailer" role="group" aria-label="...">
            <%= link_to 'Edit', edit_organization_path(organization), :type => "button", :class => "btn btn-warning" %>
            <%= link_to 'Delete', organization, :type => "button", :class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/organizations/edit.html.erb
<%= link_to 'Show', @organization %> |
<%= link_to 'Back to Admin', admin_path %>

<h1>Editing Organization</h1>

<%= render 'form' %>

app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Organizations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= link_to 'Show', organization %></td>
        <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
        <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<%= link_to 'Back to Admin', admin_path %>
<h1>New Organization</h1>

<%= render 'form' %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>


<h1><%= @organization.name %></h1>
<h3><%= @organization.description %></h3>
 <%= image_tag @organization.image.url(:medium) %>